##

learn_all {
  priority = high;

  # THIS is the critical line:
  authenticated = false;
  is_local = true;

  apply {
    classifiers {
      bayes {
        spam = true;
        ham = true;
      }
    }
  }
}

